service: service3
# frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  region: us-east-2
  profile: "${param:prof,null}"

plugins:
  - serverless-localstack

custom:
  stage: ${opt:stage, 'test'}
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: True
    docker:
      sudo: False

build:
  esbuild:
    bundle: true
    minify: true

package:
  individually: true
  patterns:
    - '!./**'

functions:
  functionE:
    handler: functionE/handler.main
    description: This is function E
    architecture: arm64
    package:
      include:
        - node_modules/**
        - functionE/**
  functionF:
    handler: functioF/handler.main
    architecture: arm64
    package:
      include:
        - node_modules/**
        - functionF/**