service: service1
# frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'local'}
  region: us-east-2
  profile: local
  

plugins:
  - serverless-localstack

custom:
  stage: ${opt:stage, 'local'}
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: False
    # networks:
    #   - localstack-net
    # lambda:
    #   mountCode: True
    # docker:
    #   sudo: False

build:
  esbuild:
    bundle: true
    minify: true

package:
  individually: true
  patterns:
    - '!./**'

functions:
  functionA:
    handler: functionA/handler.main
    description: This is function Aa
    architecture: arm64
    package:
      include:
        - node_modules/**
        - functionA/**
  functionB:
    handler: functionB/handler.main
    description: This is function Bb
    architecture: arm64
    package:
      include:
        - node_modules/**
        - functionB/**